name: Go Cross-Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [arm64, x64]

        include:
          - os: linux
            arch: arm64
          - os: linux
            arch: x64
          - os: darwin
            arch: x64
          - os: darwin
            arch: arm64
          - os: windows
            arch: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Go application
        id: build_app
        run: |
          APP_NAME="yochat"


          export GOOS=${{ matrix.os }}


          GO_ARCH_FOR_COMPILER=""
          if [ "${{ matrix.arch }}" = "x64" ]; then
            GO_ARCH_FOR_COMPILER="amd64"
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            GO_ARCH_FOR_COMPILER="arm64"
          else
            echo "Error: Unknown architecture for Go compiler: ${{ matrix.arch }}"
            exit 1
          fi
          export GOARCH="$GO_ARCH_FOR_COMPILER"

          echo "Building for $GOOS/$GOARCH..."

          EXECUTABLE_NAME="${APP_NAME}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            EXECUTABLE_NAME="${EXECUTABLE_NAME}.exe"
          fi



          CGO_ENABLED=0 go build -o "${EXECUTABLE_NAME}" ./main.go


          echo "Built executable details:"
          ls -lh "${EXECUTABLE_NAME}"



          ARTIFACT_ARCH="${{ matrix.arch }}"


          ARTIFACT_NAME="${APP_NAME}-${{ matrix.os }}-${ARTIFACT_ARCH}"


          echo "executable_name=$EXECUTABLE_NAME" >> "$GITHUB_OUTPUT"
          echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload compiled binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_app.outputs.artifact_name }}

          path: ${{ steps.build_app.outputs.executable_name }}
